### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by Troir** [Doazeok/site#2]
1. Слайдер не анимированный (в бутстрапе уже есть для этого готовые решения)
2. Текст ошибок сделать красным цветом, а то не сразу понятно, что это ошибки
3. Сделать, чтобы в поле "Количество" нельзя было вводить больше 4 цифр (http://prntscr.com/ggm4gi)
4. Текст ошибки неправильный (http://prntscr.com/ggm3a0).
5. Надо сделать, чтобы нельзя было текст вводить вообще, только цифры (https://plugins.jquery.com/maskedinput/ - хорошая либа для подобный вещей)
6. Если товаров много, должен появляться скролл (сейчас все товары вереницей стакаются) http://prntscr.com/ggm5ua
7. Как-то странно данные в новости подгружаются. Не должно быть статики (вшитых в хтмл новостей). Должен быть массив по примеру массива товаров, в котором бы описывались публикации и выводились форичем на страницу
10. Функция loadData вызывается дважды почему-то - в news.js и в start.html.
11. start.html переименовать в index.html, так правильней 
12. в start.html перенести импорт js скриптов вниз страницы (перед закрытием <body>)

**Comment by Doazeok** [comment]
09.09

**Comment by Doazeok** [comment]
Я не так понял, начал сверху вниз делать.
Тогда наоборот
