### ISSUE TITLE
Фильтр для новостей

### ISSUE THREAD

**Issue by Troir** [Doazeok/site#3]
Добавить в страницу публикаций возможность сортировать новости по дате.
Будет вверху страницы кнопка "Сортировать по дате". Кликнули один раз - стали
сортироваться от самых новых к самым старым. Кликнули еще раз - наоборот.

**Comment by Doazeok** [comment]
06.09

**Comment by Troir** [comment]
Неплохо, но есть более стандартные средства для сортировки. Из массива новостей можно сделать массив фильтруемых новостей, что-то вроде: https://stackoverflow.com/questions/20857594/knockout-filtering-on-observable-array.

Исправить на пример в ссылке.

**Comment by Doazeok** [comment]
15.09
