### ISSUE TITLE
Форматирование, рефактор

### ISSUE THREAD

**Issue by Troir** [Doazeok/site#4]
1. Стало лучше (в плане отступов и прочего), но все равно местами каша (табы лишние, нет табов, табы разной длины и т.д.).
Привести все в порядок.
3. В shop.js есть ViewModel - переименовать во что-нибудь более по смыслу подходящее, m_shop например.
4. Перенести из shop.js все кастомные правила для валидации (ko.validation.rules) в отдельный файл.
5. В shop.js: функции checChange, clickBtnOK, clickBtnNook - не относятся ни к какой модели. Надо чтобы относились к модели магазина (которая сейчас называется ViewModel).
Сделать это можно через прототайп:
ViewModel.prototype.checkChange = function() { //код }

**Comment by Doazeok** [comment]
05.09
